<a href="https://colab.research.google.com/github/ByeonJuHwan/PythonStudy/blob/main/ml01_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# `np.ndarray` 속성들

In [8]:
arr = np.ones(shape=(2,3)) # 모든 원소가 1.0인 (2,3) 모양의 배열을 생성.
arr1 = np.ones(shape=3)

In [9]:
print(arr) 
print(arr1)

[[1. 1. 1.]
 [1. 1. 1.]]
[1. 1. 1.]


In [11]:
arr.dtype # 배열 원소의 데이터 타입

dtype('float64')

In [12]:
arr.shape # 배열의 모양: 배열의 각 축(axis)을 따라서 있는 원소의 개수

(2, 3)

In [14]:
arr1.shape

(3,)

In [16]:
arr.ndim # 배열의 차원 (dimension) : 배열에서 축의 개수

2

In [18]:
arr1.ndim

1

In [20]:
arr.size # 크기 : 배열의 원소 전체 개수

6

In [24]:
arr = np.arange(10)
print(arr)
print('dtype:', arr.dtype)
print('shape:', arr.shape)
print('ndim:', arr.ndim)
print('size:', arr.size)

[0 1 2 3 4 5 6 7 8 9]
dtype: int64
shape: (10,)
ndim: 1
size: 10


# indexing

* python list : `list[i]. list[i][j], list[i][j][k], ...`
* numpy ndarray
    * arr[i], arr[i][j], arr[i][j][k]
    * arr[i], arr[i,j], arr[i,j,k]

In [27]:
arr = np.arange(1,13).reshape((3,4))
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [29]:
arr[0]

array([1, 2, 3, 4])

In [31]:
arr[0,0]

1

In [32]:
arr[0][0]

1

# slicing

## 1차원 배열 slicing

In [36]:
np.random.seed(1)
arr = np.random.randint(100, size=10)
print(arr)

[37 12 72  9 75  5 79 64 16  1]


In [39]:
arr[2:6] # [2,6) 범위의 원소드로 이루어진 부분집합(ndarray)

array([72,  9, 75,  5])

In [40]:
arr[:3] # 첫 3개 원소 자르기

array([37, 12, 72])

In [41]:
arr[-3:] # 마지막 3개 원소 자르기

array([64, 16,  1])

## 2차원 배열 slicing

In [44]:
arr = np.random.randint(100,size=(4,5))
print(arr)

[[49 57  3 68 24]
 [43 76 26 52 80]
 [41 82 15 64 68]
 [25 98 87  7 26]]


In [46]:
# 첫 2개의 row를 선택, 모든 column을 선택
arr[:2,:]

array([[49, 57,  3, 68, 24],
       [43, 76, 26, 52, 80]])

In [48]:
# 첫 2개 row을 선택, 첫 3개 column 선택
arr[:2,:3]

array([[49, 57,  3],
       [43, 76, 26]])

In [49]:
arr[:1,:1]

array([[49]])

# Shape 변경

* `np.ndarray.reshape(shape)`
* `np.ndarray.ravel()`
* `np.ndarray.flatten()`
* `np.newaxis` 속성 이용


## reshape

In [51]:
arr_1d = np.arange(12)
print(arr_1d)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [53]:
# arr_1d 배열을(4,3) shape의 2차원 배열로 변환 -> 모양이 변환된 새로운 배열이 리턴.
arr_2d = arr_1d.reshape((4,3))
print(arr_2d)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [56]:
np.reshape(arr_1d,(4,3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [58]:
# reshape을 할 때 자동으로 계산될 수 있는 차원 값에는 -1을 사용할 수 있음.
arr_2d = arr_1d.reshape((3,-1))
arr_2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [60]:
arr_2d = arr_1d.reshape((-1,4))
arr_2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [63]:
arr_2d.reshape(3*4,) # reshape(3,4)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [65]:
arr_2d.reshape((-1,))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

## `ravel` vs `flatten`

* `ravel` : 1차원으로 변환된 배열의 **"view"**를 리턴. 배열을 1개이고, 단지 모양만 다르게 보여주는 것.
* `flatten` : 1차원으로 변환된 배열의 **복사본**을 리턴. 원본 배열과는 다른 배열 생성.

In [67]:
print(arr_2d)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [73]:
flattened = arr_2d.flatten()
flattened

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [76]:
flattened[0]=100
print(flattened)
print(arr_2d) # 1차원으로 변환된 배열의 우너소를 변경하는 것이 2차원 배열에 영향을 미치지 않음.

[100   1   2   3   4   5   6   7   8   9  10  11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [78]:
raveled = arr_2d.ravel()
print(raveled)
print(arr_2d)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [79]:
raveled[0]=100
print(raveled)
print(arr_2d) # 1차원 배열의 수정 내용은 원본 2차원 배열에도 적용. 

[100   1   2   3   4   5   6   7   8   9  10  11]
[[100   1   2   3]
 [  4   5   6   7]
 [  8   9  10  11]]


## np.newaxis 속성을 사용한 차원 늘리기

In [81]:
arr = np.arange(5) # (5,) shape의 1차원 배열
print(arr)
print(arr.ndim)
print(arr.shape)

[0 1 2 3 4]
1
(5,)


In [84]:
# 배열 arr을 (1,5) shape의 2차원 배열로 전환
result = arr.reshape(1,-1) # (1,5)
result

array([[0, 1, 2, 3, 4]])

In [86]:
result = arr[np.newaxis, :]
result

array([[0, 1, 2, 3, 4]])

In [89]:
# 배열 arr을 (5,1) shape의 2차원 배열 변환
result = arr.reshape((5,1))
result

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [92]:
result = arr.reshape((-1,1)) # (5,1)
result

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [100]:
result = arr[1:3,np.newaxis]
result

array([[1],
       [2]])

# concatenate
 
* `np.concatenate([array1,arry2,...], axis=0)` : 특정 축(axis) 방향으로 이어 붙이가.
* `np.r_[array1,array2]` : 행(row)을 이어 붙이기.
* `np.c_[array1,array2]` : 열(column) 이어 붙이기.

In [101]:
a1 = np.arange(6).reshape((2,3))
print(a1)

[[0 1 2]
 [3 4 5]]


In [105]:
a2 = np.array([[10,20,30]]) # (1,3) shape
print(a2)

[[10 20 30]]


In [108]:
result = np.concatenate([a1,a2])
result

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [10, 20, 30]])

In [113]:
a3 = np.array([[100],[200]])#(2,1) shape
print(a3)

[[100]
 [200]]


In [116]:
result = np.concatenate([a1,a3], axis=1)
result

array([[  0,   1,   2, 100],
       [  3,   4,   5, 200]])

In [117]:
np.r_[a1,a2]

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [10, 20, 30]])

In [118]:
np.c_[a1,a3]

array([[  0,   1,   2, 100],
       [  3,   4,   5, 200]])

# Broadcasting

* `np.ndarray` 의 산술연산(`+,*,-,/`)읜 같은 위치(인덱스)의 원소들기리 (element-wise) 연산이 수행됨
* 서로 다른 shape을 갖는 배열들끼리 산술 연산이 가능한 경우가 있음.
    * broadcast
    

In [121]:
a1 = np.array([1,2]) # (2,)  shape의 1차원 배열
a2 = np.array([3,4,5]) # (3,) shape의 1차워 배열
# a1+a2 valueError 발생

## ndarray와 scalar의 연산

In [124]:
a1+10

array([11, 12])

In [125]:
a1 = np.array([[1],[2],[3]])
print(a1)

[[1]
 [2]
 [3]]


In [126]:
a1+10

array([[11],
       [12],
       [13]])

## 2차원 배열과 1차원배열 또는 2차원 배열에서의 broadcast

In [130]:
a1 = np.arange(6).reshape((2,-1))
a1

array([[0, 1, 2],
       [3, 4, 5]])

In [132]:
a2 = np.arange(10,40,10) # (3,)
a2

array([10, 20, 30])

In [134]:
a1+a2
# (3,) 1d array -->(1,3)2d array - >(2,3) 2d array broadcast

array([[10, 21, 32],
       [13, 24, 35]])

In [138]:
a3=np.array([[10],[20]])
a1+a3

array([[10, 11, 12],
       [23, 24, 25]])

## broadcast 활용

* 표준화 (standardization) : 평균이 0이 되고, 표준편차가 1이 되도록 변수들의 스케일을 변환하는 것.
* 정규화 (normalization) : 최솟값이 0이 되고, 최댓값이 1이 되도록 변수들의 스케일을 변환하는 것. min-max scaling

### 표준화

In [140]:
x = np.arange(1,6)
x

array([1, 2, 3, 4, 5])

In [142]:
mu = np.mean(x) # 1d-array 평균
mu

3.0

In [144]:
sigma = np.std(x) # 1d-array 표준편차
sigma

1.4142135623730951

In [146]:
x_scaled = (x-mu) / sigma
x_scaled

array([-1.41421356, -0.70710678,  0.        ,  0.70710678,  1.41421356])

In [148]:
np.mean(x_scaled)

0.0

In [149]:
np.std(x_scaled)

0.9999999999999999

### 정규화

In [152]:
xmin = np.min(x)
xmax = np.max(x)
print(xmin)
print(xmax)

1
5


In [154]:
x_normalized = (x-xmin) /(xmax - xmin) # 정규화
print(x_normalized) 

[0.   0.25 0.5  0.75 1.  ]


In [155]:
### 2차원 배열의 표준화 ,정규화

In [158]:
x = np.arange(1,7).reshape((3,-1))
x

array([[1, 2],
       [3, 4],
       [5, 6]])

2차원 배열 x를 axis = 0 방향으로 표쥰화, 정규화

In [177]:
mu = np.mean(x,axis=0)
print(mu)
sigma = np.std(x,axis=0)
print(sigma)

[3. 4.]
[1.63299316 1.63299316]


In [178]:
x_scaled = (x-mu)/sigma
print(x_scaled)

[[-1.22474487 -1.22474487]
 [ 0.          0.        ]
 [ 1.22474487  1.22474487]]


In [181]:
xmax = np.max(x,axis=0)
print(xmax)

[5 6]


In [183]:
xmin = np.min(x,axis=0)
print(xmin)

[1 2]


In [185]:
x_normalized = (x-xmin)/(xmax-xmin)
print(x_normalized)

[[0.  0. ]
 [0.5 0.5]
 [1.  1. ]]


배열 x를 axis=1 방향으로 표준화 , 정규화

In [193]:
mu = np.mean(x,axis=1, keepdims=True)
print(mu)

[[1.5]
 [3.5]
 [5.5]]


In [195]:
sigma = np.std(x,axis=1,keepdims=True)
print(sigma)

[[0.5]
 [0.5]
 [0.5]]


In [194]:
x_scaled = (x-mu)/sigma
print(x_scaled)

[[-1.  1.]
 [-1.  1.]
 [-1.  1.]]
